# Generated by Django 4.2.2 on 2023-07-07 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Programming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('DOB', models.DateField(max_length=10)),
                ('Age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('phono', models.IntegerField()),
                ('email', models.EmailField(max_length=40)),
                ('address', models.TextField(max_length=250)),
                ('purpose', models.CharField(max_length=100)),
                ('materials', models.CharField(max_length=40)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolapp.course')),
                ('departmentname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schoolapp.programming')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='programming',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.programming'),
        ),
    ]
